### ISSUE TITLE
`Read` on uninitialized buffer may cause UB

### ISSUE THREAD

**Issue by JOE1994** [SolraBizna/outer_cgi#1]
Hello fellow Rustacean,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/SolraBizna/outer_cgi/blob/a981e7e7d888c4ca4ca36f8a78732f75cc6f8224/src/fcgi.rs#L183-L196

`<fcgi::KeyValueReader<R> as std::iter::Iterator>::next()` method creates an uninitialized buffer and passes it to user-provided `Read` implementation (2 such occurrences within the same function). This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## How to fix the issue?

The Naive & safe way to fix the issue is to always zero-initialize a buffer before lending it to a user-provided `Read` implementation. Note that this approach will add runtime performance overhead of zero-initializing the buffer.

As of Jan 2021, there is not yet an ideal fix that works in stable Rust with no performance overhead. Below are links to relevant discussions & suggestions for the fix.

* [Well-written document regarding the issue](https://paper.dropbox.com/doc/IO-Buffer-Initialization-MvytTgjIOTNpJAS6Mvw38)
* [Rust RFC 2930](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary)
* [nightly feature `std::io::Initializer`](https://doc.rust-lang.org/std/io/struct.Initializer.html)
* [Discussion in Rust Internals Forum](https://internals.rust-lang.org/t/uninitialized-memory/1652)

**Comment by SolraBizna** [comment]
Sorry it took so long. I've been swamped.

Simply zero-initializing all the buffers is definitely a good enough approach for this crate, so I've done that everywhere I had uninitialized memory before. The most performance-critical buffers are heavily reused, so the performance impact is minimal. This also gave me an excuse to go through and put in all the missing `dyn`s and replace all my confusing uses of `is_ok` with the clearer `let _ =`...

Anyway, thanks very much for the report. dd59b3066e616a08e756f72de8dc3ab11b7036c4 and 9a7de8af5b54fccfea8f33001c32cecada06a79a should eliminate any possible issues from uninitialized memory.
